# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zhihu_addtask.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form_AddTask(object):
    def setupUi(self, Form_AddTask):
        Form_AddTask.setObjectName("Form_AddTask")
        Form_AddTask.resize(530, 302)
        self.label = QtWidgets.QLabel(Form_AddTask)
        self.label.setGeometry(QtCore.QRect(80, 20, 31, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form_AddTask)
        self.label_2.setGeometry(QtCore.QRect(60, 50, 41, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form_AddTask)
        self.label_3.setGeometry(QtCore.QRect(60, 80, 51, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form_AddTask)
        self.label_4.setGeometry(QtCore.QRect(60, 110, 51, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form_AddTask)
        self.label_5.setGeometry(QtCore.QRect(60, 140, 51, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form_AddTask)
        self.label_6.setGeometry(QtCore.QRect(80, 170, 31, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form_AddTask)
        self.label_7.setGeometry(QtCore.QRect(80, 200, 31, 21))
        self.label_7.setObjectName("label_7")
        self.comboBox_taskType = QtWidgets.QComboBox(Form_AddTask)
        self.comboBox_taskType.setGeometry(QtCore.QRect(120, 20, 111, 22))
        self.comboBox_taskType.setObjectName("comboBox_taskType")
        self.comboBox_taskType.addItem("")
        self.comboBox_taskType.addItem("")
        self.comboBox_taskType.addItem("")
        self.lineEdit_taskUrl = QtWidgets.QLineEdit(Form_AddTask)
        self.lineEdit_taskUrl.setGeometry(QtCore.QRect(120, 50, 351, 20))
        self.lineEdit_taskUrl.setObjectName("lineEdit_taskUrl")
        self.lineEdit_taskCount = QtWidgets.QLineEdit(Form_AddTask)
        self.lineEdit_taskCount.setGeometry(QtCore.QRect(120, 80, 113, 20))
        self.lineEdit_taskCount.setObjectName("lineEdit_taskCount")
        self.lineEdit_taskCustomer = QtWidgets.QLineEdit(Form_AddTask)
        self.lineEdit_taskCustomer.setGeometry(QtCore.QRect(120, 170, 113, 20))
        self.lineEdit_taskCustomer.setObjectName("lineEdit_taskCustomer")
        self.lineEdit_taskRemark = QtWidgets.QLineEdit(Form_AddTask)
        self.lineEdit_taskRemark.setGeometry(QtCore.QRect(120, 200, 113, 20))
        self.lineEdit_taskRemark.setObjectName("lineEdit_taskRemark")
        self.comboBox_taskInterval = QtWidgets.QComboBox(Form_AddTask)
        self.comboBox_taskInterval.setGeometry(QtCore.QRect(120, 110, 111, 22))
        self.comboBox_taskInterval.setObjectName("comboBox_taskInterval")
        self.comboBox_taskInterval.addItem("")
        self.comboBox_taskInterval.addItem("")
        self.comboBox_taskInterval.addItem("")
        self.comboBox_taskInterval.addItem("")
        self.comboBox_taskInterval.addItem("")
        self.comboBox_taskOrder = QtWidgets.QComboBox(Form_AddTask)
        self.comboBox_taskOrder.setGeometry(QtCore.QRect(120, 140, 111, 22))
        self.comboBox_taskOrder.setObjectName("comboBox_taskOrder")
        self.comboBox_taskOrder.addItem("")
        self.comboBox_taskOrder.addItem("")
        self.comboBox_taskOrder.addItem("")
        self.pushButton_addTask = QtWidgets.QPushButton(Form_AddTask)
        self.pushButton_addTask.setGeometry(QtCore.QRect(180, 250, 75, 23))
        self.pushButton_addTask.setObjectName("pushButton_addTask")
        self.pushButton_clearTask = QtWidgets.QPushButton(Form_AddTask)
        self.pushButton_clearTask.setGeometry(QtCore.QRect(310, 250, 75, 23))
        self.pushButton_clearTask.setObjectName("pushButton_clearTask")

        self.retranslateUi(Form_AddTask)
        QtCore.QMetaObject.connectSlotsByName(Form_AddTask)

    def retranslateUi(self, Form_AddTask):
        _translate = QtCore.QCoreApplication.translate
        Form_AddTask.setWindowTitle(_translate("Form_AddTask", "新增任务"))
        self.label.setText(_translate("Form_AddTask", "类型"))
        self.label_2.setText(_translate("Form_AddTask", "任务url"))
        self.label_3.setText(_translate("Form_AddTask", "任务数量"))
        self.label_4.setText(_translate("Form_AddTask", "时间间隔"))
        self.label_5.setText(_translate("Form_AddTask", "执行顺序"))
        self.label_6.setText(_translate("Form_AddTask", "客户"))
        self.label_7.setText(_translate("Form_AddTask", "备注"))
        self.comboBox_taskType.setItemText(0, _translate("Form_AddTask", "问题赞同"))
        self.comboBox_taskType.setItemText(1, _translate("Form_AddTask", "问题反对"))
        self.comboBox_taskType.setItemText(2, _translate("Form_AddTask", "用户关注"))
        self.comboBox_taskInterval.setItemText(0, _translate("Form_AddTask", "0"))
        self.comboBox_taskInterval.setItemText(1, _translate("Form_AddTask", "10"))
        self.comboBox_taskInterval.setItemText(2, _translate("Form_AddTask", "30"))
        self.comboBox_taskInterval.setItemText(3, _translate("Form_AddTask", "60"))
        self.comboBox_taskInterval.setItemText(4, _translate("Form_AddTask", "120"))
        self.comboBox_taskOrder.setItemText(0, _translate("Form_AddTask", "正常"))
        self.comboBox_taskOrder.setItemText(1, _translate("Form_AddTask", "优先"))
        self.comboBox_taskOrder.setItemText(2, _translate("Form_AddTask", "稍后"))
        self.pushButton_addTask.setText(_translate("Form_AddTask", "新增"))
        self.pushButton_clearTask.setText(_translate("Form_AddTask", "清空"))

