# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zhihu.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(819, 581)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 821, 581))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_task = QtWidgets.QWidget()
        self.tab_task.setObjectName("tab_task")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab_task)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(80, 10, 331, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_addTask = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_addTask.setObjectName("pushButton_addTask")
        self.horizontalLayout.addWidget(self.pushButton_addTask)
        self.pushButton_deleteTask = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_deleteTask.setObjectName("pushButton_deleteTask")
        self.horizontalLayout.addWidget(self.pushButton_deleteTask)
        self.pushButton_updateTask = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_updateTask.setObjectName("pushButton_updateTask")
        self.horizontalLayout.addWidget(self.pushButton_updateTask)
        self.pushButton_queryTask = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_queryTask.setObjectName("pushButton_queryTask")
        self.horizontalLayout.addWidget(self.pushButton_queryTask)
        self.tableWidget_task = QtWidgets.QTableWidget(self.tab_task)
        self.tableWidget_task.setGeometry(QtCore.QRect(10, 50, 791, 501))
        self.tableWidget_task.setObjectName("tableWidget_task")
        self.tableWidget_task.setColumnCount(13)
        self.tableWidget_task.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_task.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_task.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_task.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_task.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_task.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_task.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_task.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_task.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_task.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_task.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_task.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_task.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_task.setHorizontalHeaderItem(12, item)
        self.pushButton_startTask = QtWidgets.QPushButton(self.tab_task)
        self.pushButton_startTask.setGeometry(QtCore.QRect(550, 10, 112, 31))
        self.pushButton_startTask.setObjectName("pushButton_startTask")
        self.pushButton_stopTask = QtWidgets.QPushButton(self.tab_task)
        self.pushButton_stopTask.setGeometry(QtCore.QRect(670, 10, 111, 31))
        self.pushButton_stopTask.setObjectName("pushButton_stopTask")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.tab_task)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(10, 10, 51, 31))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_selectAllTask = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.pushButton_selectAllTask.setObjectName("pushButton_selectAllTask")
        self.horizontalLayout_7.addWidget(self.pushButton_selectAllTask)
        self.tabWidget.addTab(self.tab_task, "")
        self.tab_account = QtWidgets.QWidget()
        self.tab_account.setObjectName("tab_account")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab_account)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(80, 10, 251, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_importAccount = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_importAccount.setObjectName("pushButton_importAccount")
        self.horizontalLayout_2.addWidget(self.pushButton_importAccount)
        self.pushButton_exportAccount = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_exportAccount.setObjectName("pushButton_exportAccount")
        self.horizontalLayout_2.addWidget(self.pushButton_exportAccount)
        self.pushButton_deleteAccount = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_deleteAccount.setObjectName("pushButton_deleteAccount")
        self.horizontalLayout_2.addWidget(self.pushButton_deleteAccount)
        self.tableWidget_account = QtWidgets.QTableWidget(self.tab_account)
        self.tableWidget_account.setGeometry(QtCore.QRect(10, 50, 791, 501))
        self.tableWidget_account.setObjectName("tableWidget_account")
        self.tableWidget_account.setColumnCount(0)
        self.tableWidget_account.setRowCount(0)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tab_account)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(440, 10, 161, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_updateAccount = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_updateAccount.setObjectName("pushButton_updateAccount")
        self.horizontalLayout_3.addWidget(self.pushButton_updateAccount)
        self.pushButton_queryAccount = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_queryAccount.setObjectName("pushButton_queryAccount")
        self.horizontalLayout_3.addWidget(self.pushButton_queryAccount)
        self.label_7 = QtWidgets.QLabel(self.tab_account)
        self.label_7.setGeometry(QtCore.QRect(340, 10, 31, 31))
        self.label_7.setObjectName("label_7")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.tab_account)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(370, 10, 61, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.comboBox_accountStatus = QtWidgets.QComboBox(self.horizontalLayoutWidget_4)
        self.comboBox_accountStatus.setObjectName("comboBox_accountStatus")
        self.horizontalLayout_4.addWidget(self.comboBox_accountStatus)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.tab_account)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 10, 51, 31))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_selectAllAccount = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.pushButton_selectAllAccount.setObjectName("pushButton_selectAllAccount")
        self.horizontalLayout_6.addWidget(self.pushButton_selectAllAccount)
        self.pushButton_registerAccount = QtWidgets.QPushButton(self.tab_account)
        self.pushButton_registerAccount.setGeometry(QtCore.QRect(670, 10, 111, 31))
        self.pushButton_registerAccount.setObjectName("pushButton_registerAccount")
        self.tabWidget.addTab(self.tab_account, "")
        self.tab_setting = QtWidgets.QWidget()
        self.tab_setting.setObjectName("tab_setting")
        self.groupBox_networkSetting = QtWidgets.QGroupBox(self.tab_setting)
        self.groupBox_networkSetting.setGeometry(QtCore.QRect(40, 20, 741, 80))
        self.groupBox_networkSetting.setObjectName("groupBox_networkSetting")
        self.radioButton_benjiwangluo = QtWidgets.QRadioButton(self.groupBox_networkSetting)
        self.radioButton_benjiwangluo.setGeometry(QtCore.QRect(90, 30, 89, 31))
        self.radioButton_benjiwangluo.setObjectName("radioButton_benjiwangluo")
        self.radioButton_dongtaiip = QtWidgets.QRadioButton(self.groupBox_networkSetting)
        self.radioButton_dongtaiip.setGeometry(QtCore.QRect(340, 30, 89, 31))
        self.radioButton_dongtaiip.setObjectName("radioButton_dongtaiip")
        self.radioButton_adslbohao = QtWidgets.QRadioButton(self.groupBox_networkSetting)
        self.radioButton_adslbohao.setGeometry(QtCore.QRect(580, 30, 89, 31))
        self.radioButton_adslbohao.setObjectName("radioButton_adslbohao")
        self.groupBox_dama = QtWidgets.QGroupBox(self.tab_setting)
        self.groupBox_dama.setGeometry(QtCore.QRect(40, 170, 741, 91))
        self.groupBox_dama.setObjectName("groupBox_dama")
        self.comboBox_damapingtai = QtWidgets.QComboBox(self.groupBox_dama)
        self.comboBox_damapingtai.setGeometry(QtCore.QRect(90, 40, 69, 22))
        self.comboBox_damapingtai.setObjectName("comboBox_damapingtai")
        self.comboBox_damapingtai.addItem("")
        self.comboBox_damapingtai.addItem("")
        self.comboBox_damapingtai.addItem("")
        self.comboBox_damapingtai.addItem("")
        self.comboBox_damapingtai.addItem("")
        self.comboBox_damapingtai.addItem("")
        self.label = QtWidgets.QLabel(self.groupBox_dama)
        self.label.setGeometry(QtCore.QRect(30, 40, 54, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_dama)
        self.label_2.setGeometry(QtCore.QRect(200, 40, 31, 21))
        self.label_2.setObjectName("label_2")
        self.lineEdit_damazhanghao = QtWidgets.QLineEdit(self.groupBox_dama)
        self.lineEdit_damazhanghao.setGeometry(QtCore.QRect(230, 40, 113, 20))
        self.lineEdit_damazhanghao.setText("")
        self.lineEdit_damazhanghao.setObjectName("lineEdit_damazhanghao")
        self.label_3 = QtWidgets.QLabel(self.groupBox_dama)
        self.label_3.setGeometry(QtCore.QRect(370, 40, 31, 20))
        self.label_3.setObjectName("label_3")
        self.lineEdit_damamima = QtWidgets.QLineEdit(self.groupBox_dama)
        self.lineEdit_damamima.setGeometry(QtCore.QRect(400, 40, 113, 20))
        self.lineEdit_damamima.setText("")
        self.lineEdit_damamima.setObjectName("lineEdit_damamima")
        self.pushButton_damadenglu = QtWidgets.QPushButton(self.groupBox_dama)
        self.pushButton_damadenglu.setGeometry(QtCore.QRect(550, 40, 75, 23))
        self.pushButton_damadenglu.setObjectName("pushButton_damadenglu")
        self.pushButton_damazhuce = QtWidgets.QPushButton(self.groupBox_dama)
        self.pushButton_damazhuce.setGeometry(QtCore.QRect(640, 40, 75, 23))
        self.pushButton_damazhuce.setObjectName("pushButton_damazhuce")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_dama)
        self.pushButton_3.setGeometry(QtCore.QRect(600, 190, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.groupBox_jiema = QtWidgets.QGroupBox(self.tab_setting)
        self.groupBox_jiema.setGeometry(QtCore.QRect(40, 340, 741, 91))
        self.groupBox_jiema.setObjectName("groupBox_jiema")
        self.label_4 = QtWidgets.QLabel(self.groupBox_jiema)
        self.label_4.setGeometry(QtCore.QRect(30, 40, 54, 21))
        self.label_4.setObjectName("label_4")
        self.comboBox_jimapingtai = QtWidgets.QComboBox(self.groupBox_jiema)
        self.comboBox_jimapingtai.setGeometry(QtCore.QRect(90, 40, 69, 22))
        self.comboBox_jimapingtai.setObjectName("comboBox_jimapingtai")
        self.comboBox_jimapingtai.addItem("")
        self.comboBox_jimapingtai.addItem("")
        self.label_5 = QtWidgets.QLabel(self.groupBox_jiema)
        self.label_5.setGeometry(QtCore.QRect(200, 40, 31, 21))
        self.label_5.setObjectName("label_5")
        self.lineEdit_jiemazhanghao = QtWidgets.QLineEdit(self.groupBox_jiema)
        self.lineEdit_jiemazhanghao.setGeometry(QtCore.QRect(230, 40, 113, 20))
        self.lineEdit_jiemazhanghao.setText("")
        self.lineEdit_jiemazhanghao.setObjectName("lineEdit_jiemazhanghao")
        self.label_6 = QtWidgets.QLabel(self.groupBox_jiema)
        self.label_6.setGeometry(QtCore.QRect(370, 40, 31, 21))
        self.label_6.setObjectName("label_6")
        self.lineEdit_jiemamima = QtWidgets.QLineEdit(self.groupBox_jiema)
        self.lineEdit_jiemamima.setGeometry(QtCore.QRect(400, 40, 113, 20))
        self.lineEdit_jiemamima.setText("")
        self.lineEdit_jiemamima.setObjectName("lineEdit_jiemamima")
        self.pushButton_jiemadenglu = QtWidgets.QPushButton(self.groupBox_jiema)
        self.pushButton_jiemadenglu.setGeometry(QtCore.QRect(550, 40, 75, 23))
        self.pushButton_jiemadenglu.setObjectName("pushButton_jiemadenglu")
        self.pushButton_jiemazhuce = QtWidgets.QPushButton(self.groupBox_jiema)
        self.pushButton_jiemazhuce.setGeometry(QtCore.QRect(640, 40, 75, 23))
        self.pushButton_jiemazhuce.setObjectName("pushButton_jiemazhuce")
        self.tabWidget.addTab(self.tab_setting, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "知乎营销助手"))
        self.pushButton_addTask.setText(_translate("Form", "新增"))
        self.pushButton_deleteTask.setText(_translate("Form", "删除"))
        self.pushButton_updateTask.setText(_translate("Form", "修改"))
        self.pushButton_queryTask.setText(_translate("Form", "查询"))
        item = self.tableWidget_task.horizontalHeaderItem(1)
        item.setText(_translate("Form", "类型"))
        item = self.tableWidget_task.horizontalHeaderItem(2)
        item.setText(_translate("Form", "任务url"))
        item = self.tableWidget_task.horizontalHeaderItem(3)
        item.setText(_translate("Form", "任务数量"))
        item = self.tableWidget_task.horizontalHeaderItem(4)
        item.setText(_translate("Form", "初始数量"))
        item = self.tableWidget_task.horizontalHeaderItem(5)
        item.setText(_translate("Form", "当前数量"))
        item = self.tableWidget_task.horizontalHeaderItem(6)
        item.setText(_translate("Form", "执行状态"))
        item = self.tableWidget_task.horizontalHeaderItem(7)
        item.setText(_translate("Form", "执行顺序"))
        item = self.tableWidget_task.horizontalHeaderItem(8)
        item.setText(_translate("Form", "时间间隔"))
        item = self.tableWidget_task.horizontalHeaderItem(9)
        item.setText(_translate("Form", "客户"))
        item = self.tableWidget_task.horizontalHeaderItem(10)
        item.setText(_translate("Form", "是否发货"))
        item = self.tableWidget_task.horizontalHeaderItem(11)
        item.setText(_translate("Form", "备注"))
        item = self.tableWidget_task.horizontalHeaderItem(12)
        item.setText(_translate("Form", "id"))
        self.pushButton_startTask.setText(_translate("Form", "开始任务"))
        self.pushButton_stopTask.setText(_translate("Form", "停止任务"))
        self.pushButton_selectAllTask.setText(_translate("Form", "全选"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_task), _translate("Form", "任务管理"))
        self.pushButton_importAccount.setText(_translate("Form", "导入"))
        self.pushButton_exportAccount.setText(_translate("Form", "导出"))
        self.pushButton_deleteAccount.setText(_translate("Form", "删除"))
        self.pushButton_updateAccount.setText(_translate("Form", "修改"))
        self.pushButton_queryAccount.setText(_translate("Form", "查询"))
        self.label_7.setText(_translate("Form", "状态"))
        self.pushButton_selectAllAccount.setText(_translate("Form", "全选"))
        self.pushButton_registerAccount.setText(_translate("Form", "账号注册"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_account), _translate("Form", "账号管理"))
        self.groupBox_networkSetting.setTitle(_translate("Form", "网络设置"))
        self.radioButton_benjiwangluo.setText(_translate("Form", "本机网络"))
        self.radioButton_dongtaiip.setText(_translate("Form", "动态IP"))
        self.radioButton_adslbohao.setText(_translate("Form", "ADSL拨号"))
        self.groupBox_dama.setTitle(_translate("Form", "打码设置"))
        self.comboBox_damapingtai.setItemText(0, _translate("Form", "若快"))
        self.comboBox_damapingtai.setItemText(1, _translate("Form", "联众"))
        self.comboBox_damapingtai.setItemText(2, _translate("Form", "云速"))
        self.comboBox_damapingtai.setItemText(3, _translate("Form", "乱码"))
        self.comboBox_damapingtai.setItemText(4, _translate("Form", "优优云"))
        self.comboBox_damapingtai.setItemText(5, _translate("Form", "超人打码"))
        self.label.setText(_translate("Form", "打码平台"))
        self.label_2.setText(_translate("Form", "账号"))
        self.label_3.setText(_translate("Form", "密码"))
        self.pushButton_damadenglu.setText(_translate("Form", "登录"))
        self.pushButton_damazhuce.setText(_translate("Form", "注册/充值"))
        self.pushButton_3.setText(_translate("Form", "登录"))
        self.groupBox_jiema.setTitle(_translate("Form", "接码设置"))
        self.label_4.setText(_translate("Form", "接码平台"))
        self.comboBox_jimapingtai.setItemText(0, _translate("Form", "神话"))
        self.comboBox_jimapingtai.setItemText(1, _translate("Form", "基码"))
        self.label_5.setText(_translate("Form", "账号"))
        self.label_6.setText(_translate("Form", "密码"))
        self.pushButton_jiemadenglu.setText(_translate("Form", "登录"))
        self.pushButton_jiemazhuce.setText(_translate("Form", "注册/充值"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_setting), _translate("Form", "软件设置"))

