# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zhihu_querytask.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form_QueryTask(object):
    def setupUi(self, Form_QueryTask):
        Form_QueryTask.setObjectName("Form_QueryTask")
        Form_QueryTask.resize(531, 414)
        self.label = QtWidgets.QLabel(Form_QueryTask)
        self.label.setGeometry(QtCore.QRect(80, 20, 31, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form_QueryTask)
        self.label_2.setGeometry(QtCore.QRect(60, 50, 41, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form_QueryTask)
        self.label_3.setGeometry(QtCore.QRect(60, 80, 51, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form_QueryTask)
        self.label_4.setGeometry(QtCore.QRect(60, 230, 51, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form_QueryTask)
        self.label_5.setGeometry(QtCore.QRect(60, 200, 51, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form_QueryTask)
        self.label_6.setGeometry(QtCore.QRect(80, 260, 31, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form_QueryTask)
        self.label_7.setGeometry(QtCore.QRect(80, 320, 31, 21))
        self.label_7.setObjectName("label_7")
        self.comboBox_taskType = QtWidgets.QComboBox(Form_QueryTask)
        self.comboBox_taskType.setGeometry(QtCore.QRect(120, 20, 111, 22))
        self.comboBox_taskType.setObjectName("comboBox_taskType")
        self.comboBox_taskType.addItem("")
        self.comboBox_taskType.setItemText(0, "")
        self.comboBox_taskType.addItem("")
        self.comboBox_taskType.addItem("")
        self.comboBox_taskType.addItem("")
        self.lineEdit_taskUrl = QtWidgets.QLineEdit(Form_QueryTask)
        self.lineEdit_taskUrl.setGeometry(QtCore.QRect(120, 50, 351, 20))
        self.lineEdit_taskUrl.setObjectName("lineEdit_taskUrl")
        self.lineEdit_taskCount = QtWidgets.QLineEdit(Form_QueryTask)
        self.lineEdit_taskCount.setGeometry(QtCore.QRect(120, 80, 113, 20))
        self.lineEdit_taskCount.setObjectName("lineEdit_taskCount")
        self.lineEdit_taskCustomer = QtWidgets.QLineEdit(Form_QueryTask)
        self.lineEdit_taskCustomer.setGeometry(QtCore.QRect(120, 260, 113, 20))
        self.lineEdit_taskCustomer.setObjectName("lineEdit_taskCustomer")
        self.lineEdit_taskRemark = QtWidgets.QLineEdit(Form_QueryTask)
        self.lineEdit_taskRemark.setGeometry(QtCore.QRect(120, 320, 111, 20))
        self.lineEdit_taskRemark.setObjectName("lineEdit_taskRemark")
        self.comboBox_taskInterval = QtWidgets.QComboBox(Form_QueryTask)
        self.comboBox_taskInterval.setGeometry(QtCore.QRect(120, 230, 111, 22))
        self.comboBox_taskInterval.setObjectName("comboBox_taskInterval")
        self.comboBox_taskInterval.addItem("")
        self.comboBox_taskInterval.setItemText(0, "")
        self.comboBox_taskInterval.addItem("")
        self.comboBox_taskInterval.addItem("")
        self.comboBox_taskInterval.addItem("")
        self.comboBox_taskInterval.addItem("")
        self.comboBox_taskInterval.addItem("")
        self.comboBox_taskOrder = QtWidgets.QComboBox(Form_QueryTask)
        self.comboBox_taskOrder.setGeometry(QtCore.QRect(120, 200, 111, 22))
        self.comboBox_taskOrder.setObjectName("comboBox_taskOrder")
        self.comboBox_taskOrder.addItem("")
        self.comboBox_taskOrder.setItemText(0, "")
        self.comboBox_taskOrder.addItem("")
        self.comboBox_taskOrder.addItem("")
        self.comboBox_taskOrder.addItem("")
        self.pushButton_queryTask = QtWidgets.QPushButton(Form_QueryTask)
        self.pushButton_queryTask.setGeometry(QtCore.QRect(180, 370, 75, 23))
        self.pushButton_queryTask.setObjectName("pushButton_queryTask")
        self.pushButton_clearTask = QtWidgets.QPushButton(Form_QueryTask)
        self.pushButton_clearTask.setGeometry(QtCore.QRect(310, 370, 75, 23))
        self.pushButton_clearTask.setObjectName("pushButton_clearTask")
        self.label_8 = QtWidgets.QLabel(Form_QueryTask)
        self.label_8.setGeometry(QtCore.QRect(60, 110, 51, 21))
        self.label_8.setObjectName("label_8")
        self.lineEdit_taskBeginCount = QtWidgets.QLineEdit(Form_QueryTask)
        self.lineEdit_taskBeginCount.setGeometry(QtCore.QRect(120, 110, 113, 20))
        self.lineEdit_taskBeginCount.setObjectName("lineEdit_taskBeginCount")
        self.label_9 = QtWidgets.QLabel(Form_QueryTask)
        self.label_9.setGeometry(QtCore.QRect(60, 170, 51, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form_QueryTask)
        self.label_10.setGeometry(QtCore.QRect(60, 290, 51, 21))
        self.label_10.setObjectName("label_10")
        self.comboBox_taskStatus = QtWidgets.QComboBox(Form_QueryTask)
        self.comboBox_taskStatus.setGeometry(QtCore.QRect(120, 170, 111, 22))
        self.comboBox_taskStatus.setObjectName("comboBox_taskStatus")
        self.comboBox_taskStatus.addItem("")
        self.comboBox_taskStatus.setItemText(0, "")
        self.comboBox_taskStatus.addItem("")
        self.comboBox_taskStatus.addItem("")
        self.comboBox_taskStatus.addItem("")
        self.comboBox_taskStatus.addItem("")
        self.comboBox_taskStatus.addItem("")
        self.comboBox_taskDeliver = QtWidgets.QComboBox(Form_QueryTask)
        self.comboBox_taskDeliver.setGeometry(QtCore.QRect(120, 290, 111, 22))
        self.comboBox_taskDeliver.setObjectName("comboBox_taskDeliver")
        self.comboBox_taskDeliver.addItem("")
        self.comboBox_taskDeliver.setItemText(0, "")
        self.comboBox_taskDeliver.addItem("")
        self.comboBox_taskDeliver.addItem("")
        self.label_11 = QtWidgets.QLabel(Form_QueryTask)
        self.label_11.setGeometry(QtCore.QRect(60, 140, 51, 21))
        self.label_11.setObjectName("label_11")
        self.lineEdit_taskCurrentCount = QtWidgets.QLineEdit(Form_QueryTask)
        self.lineEdit_taskCurrentCount.setGeometry(QtCore.QRect(120, 140, 113, 20))
        self.lineEdit_taskCurrentCount.setObjectName("lineEdit_taskCurrentCount")

        self.retranslateUi(Form_QueryTask)
        QtCore.QMetaObject.connectSlotsByName(Form_QueryTask)

    def retranslateUi(self, Form_QueryTask):
        _translate = QtCore.QCoreApplication.translate
        Form_QueryTask.setWindowTitle(_translate("Form_QueryTask", "查询任务"))
        self.label.setText(_translate("Form_QueryTask", "类型"))
        self.label_2.setText(_translate("Form_QueryTask", "任务url"))
        self.label_3.setText(_translate("Form_QueryTask", "任务数量"))
        self.label_4.setText(_translate("Form_QueryTask", "时间间隔"))
        self.label_5.setText(_translate("Form_QueryTask", "执行顺序"))
        self.label_6.setText(_translate("Form_QueryTask", "客户"))
        self.label_7.setText(_translate("Form_QueryTask", "备注"))
        self.comboBox_taskType.setItemText(1, _translate("Form_QueryTask", "问题赞同"))
        self.comboBox_taskType.setItemText(2, _translate("Form_QueryTask", "问题反对"))
        self.comboBox_taskType.setItemText(3, _translate("Form_QueryTask", "用户关注"))
        self.comboBox_taskInterval.setItemText(1, _translate("Form_QueryTask", "0"))
        self.comboBox_taskInterval.setItemText(2, _translate("Form_QueryTask", "10"))
        self.comboBox_taskInterval.setItemText(3, _translate("Form_QueryTask", "30"))
        self.comboBox_taskInterval.setItemText(4, _translate("Form_QueryTask", "60"))
        self.comboBox_taskInterval.setItemText(5, _translate("Form_QueryTask", "120"))
        self.comboBox_taskOrder.setItemText(1, _translate("Form_QueryTask", "正常"))
        self.comboBox_taskOrder.setItemText(2, _translate("Form_QueryTask", "优先"))
        self.comboBox_taskOrder.setItemText(3, _translate("Form_QueryTask", "稍后"))
        self.pushButton_queryTask.setText(_translate("Form_QueryTask", "查询"))
        self.pushButton_clearTask.setText(_translate("Form_QueryTask", "清空"))
        self.label_8.setText(_translate("Form_QueryTask", "初始数量"))
        self.label_9.setText(_translate("Form_QueryTask", "执行状态"))
        self.label_10.setText(_translate("Form_QueryTask", "是否发货"))
        self.comboBox_taskStatus.setItemText(1, _translate("Form_QueryTask", "新建"))
        self.comboBox_taskStatus.setItemText(2, _translate("Form_QueryTask", "待执行"))
        self.comboBox_taskStatus.setItemText(3, _translate("Form_QueryTask", "执行中"))
        self.comboBox_taskStatus.setItemText(4, _translate("Form_QueryTask", "完成"))
        self.comboBox_taskStatus.setItemText(5, _translate("Form_QueryTask", "错误"))
        self.comboBox_taskDeliver.setItemText(1, _translate("Form_QueryTask", "否"))
        self.comboBox_taskDeliver.setItemText(2, _translate("Form_QueryTask", "是"))
        self.label_11.setText(_translate("Form_QueryTask", "当前数量"))

